import { useEffect, useState } from "react";
import AppShell from "../components/AppShell";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";
import "./Tickets.css";

const blankAgent = { name: "", email: "", password: "" };
export default function Agents() {
  const { user } = useAuth(); const [agents, setAgents] = useState([]); const [error, setError] = useState(""); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(blankAgent); const [saving, setSaving] = useState(false);
  const load = async () => { try { const { data } = await api.get("/api/users", { params: { include_inactive: true } }); setAgents(data); } catch (err) { setError(err.response?.data?.detail || "Could not load agents."); } };
  useEffect(() => { if (user?.role === "admin") load(); }, [user?.role]);
  const create = async (event) => { event.preventDefault(); setSaving(true); try { await api.post("/api/users", form); setForm(blankAgent); setShowForm(false); await load(); } catch (err) { setError(err.response?.data?.detail || "Could not create agent."); } finally { setSaving(false); } };
  const toggle = async (agent) => { try { await api.patch(`/api/users/${agent.id}`, { is_active: !agent.is_active }); await load(); } catch (err) { setError(err.response?.data?.detail || "Could not update agent."); } };
  if (user?.role !== "admin") return <AppShell title="Agents"><div className="alert error">Only administrators can manage agents.</div></AppShell>;
  return <AppShell title="Agents"><div className="page-intro"><div><h2>Team management</h2><p>You approve each employee before they can sign in.</p></div><button className="primary" onClick={() => setShowForm(true)}>+ Add employee</button></div>{error && <div className="alert error">{error}</div>}<section className="table-card"><div className="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Access</th><th /></tr></thead><tbody>{agents.map((agent) => <tr key={agent.id}><td><strong>{agent.name}</strong></td><td>{agent.email}</td><td><span className="pill status-open">{agent.role}</span></td><td><span className={`pill ${agent.is_active ? "status-resolved" : "status-closed"}`}>{agent.is_active ? "Approved" : "Awaiting approval"}</span></td><td><button className="secondary" disabled={agent.id === user.id} onClick={() => toggle(agent)}>{agent.is_active ? "Revoke access" : "Approve access"}</button></td></tr>)}</tbody></table></div></section>{showForm && <div className="modal-backdrop"><form className="modal" onSubmit={create}><div className="modal-title"><h2>Add employee</h2><button type="button" className="icon-button" onClick={() => setShowForm(false)}>×</button></div><p className="muted">New employees are agents and must be approved before they can sign in.</p><label>Name<input required minLength="2" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Temporary password<input required type="password" minLength="8" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><div className="modal-actions"><button type="button" className="secondary" onClick={() => setShowForm(false)}>Cancel</button><button className="primary" disabled={saving}>{saving ? "Adding…" : "Add employee"}</button></div></form></div>}</AppShell>;
}
